### ISSUE TITLE
Mean File Dimensions

### ISSUE THREAD

**Issue by chandrasg** [aimerykong/deepImageAestheticsAnalysis#11]
Hi,

I am trying to run the python classification code on my previously installed caffe (not customCaffe).
I get the following error:

`Shape mean_array :  (3, 256, 256)
Shape net :  (1, 3, 227, 227)
Traceback (most recent call last):
  File "caffe_prediction.py", line 75, in <module>
    transformer.set_mean(input_layer, mean_array)
  File "/usr/local/lib/python2.7/site-packages/caffe/io.py", line 259, in set_mean
    raise ValueError('Mean shape incompatible with input shape.')
ValueError: Mean shape incompatible with input shape.`

Do I need to build customCaffe to run this? Or is it an issue with the shape of the meanfile?

**Comment by aimerykong** [comment]
Hi, the error explains that the input mean has different size from the one required in the proto file. I guess one remedy is to crop the input mean into 3x227x227, and reshape it into 4-way tensor of size 1x3x227x227. Hope this helps.

**Comment by chandrasg** [comment]
Thanks! I tried that. I get the error: 
Traceback (most recent call last):
  File "caffe_prediction.py", line 101, in <module>
    out = net.forward([img])
  File "/usr/local/lib/python2.7/site-packages/caffe/pycaffe.py", line 109, in _Net_forward
    outputs = set(self.outputs + blobs)
TypeError: unhashable type: ‘numpy.ndarray’

Do I need to compile customCaffe to get predictions?

**Comment by aimerykong** [comment]
Hi, as I didn't use python interface, I'd suggest compiling the provided
customCaffe which has new layers. When you compile customCaffe, you only
need to do it using the following. You don't need to run test cases as I
didn't write test code for the new layers.

make all -j

**Comment by chandrasg** [comment]
Thanks!

I am trying to avoid recompiling caffe since I have some system permission issues. 

Do I need to recompile customCaffe even if I use the matlab code?

**Comment by aimerykong** [comment]
I'm afraid you have to compile the customCaffe to run it.

But before that, I want to make sure that you can run the demo in matlab (
https://github.com/aimerykong/deepImageAestheticsAnalysis/tree/master/demoRatingImages
)

If you can run it and you don't want to train models, then you don't need
to compile customCaffe for matlab; otherwise, compiling it is unavoidable.

**Comment by chandrasg** [comment]
I managed to build customCaffe on another machine (with no MATLAB) — so I am left with only python interface.

The code works! But, 
out = net.predict([img])
print out

Prints only a score: [[ 0.38690358]]

and not:
#{'fc9_ColorHarmony': array([[ 0.22087261]], dtype=float32), 'fc9_MotionBlur': array([[-0.08059776]], dtype=float32), 'fc9_Light': array([[ 0.14933866]], dtype=float32), 'fc9_Content': array([[ 0.01467544]], dtype=float32), 'fc9_Repetition': array([[ 0.18157494]], dtype=float32), 'fc11_score': array([[ 0.55613178]], dtype=float32), 'fc9_DoF': array([[-0.05279735]], dtype=float32), 'fc9_VividColor': array([[ 0.13607402]], dtype=float32), 'fc9_Symmetry': array([[ 0.06802807]], dtype=float32), 'fc9_Object': array([[ 0.00289625]], dtype=float32), 'fc9_BalancingElement': array([[-0.04946293]], dtype=float32), 'fc9_RuleOfThirds': array([[-0.0477073]], dtype=float32)}

Any idea what’s going wrong? 
I get the following error: 

pred_score = out['fc11_score'][0][0]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by chandrasg** [comment]
That’s when I modify the network initialization to Classifier. 
If I use the code that’s in the repo, the error I see is:
    out = net.forward([img])
  File “caffeCustom/python/caffe/pycaffe.py", line 92, in _Net_forward
    outputs = set(self.outputs + blobs)
TypeError: unhashable type: ‘numpy.ndarray'

**Comment by chandrasg** [comment]
My bad!

The code works now!

Thanks.

**Comment by csyanbin** [comment]
According to the Matlab code in: https://github.com/aimerykong/deepImageAestheticsAnalysis/blob/master/demoRatingImages/main_demo4_suggestion.m#L52
It seems that at python code: https://github.com/aimerykong/deepImageAestheticsAnalysis/blob/master/python/caffe_prediction.py#L52
you should add: **mean_array = mean_array[:, 15:242,15:242]**

**Comment by aimerykong** [comment]
Thanks for noticing me that!
